###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "My first blog",
  "author": "Aggiovato",
  "url": "https://my-first-blog.com/",
  "likes": 18
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "",
  "author": "JavaScript",
  "url": "https://js.about-us.com",
  "likes": 500
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "React vs Angular",
  "url": "https://react.bestframeworkever.com",
  "likes": 0
}