###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Async/Await in JavaScript",
    "author": "Jane Smith",
    "url": "https://example.com/async-await",
    "likes": 18
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "",
  "author": "JavaScript",
  "url": "https://js.about-us.com",
  "likes": 500
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "React vs Angular",
  "url": "https://react.bestframeworkever.com",
  "likes": 0
}